# Generated by Django 2.1.1 on 2019-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=2048, null=True)),
                ('name', models.CharField(max_length=2048)),
                ('year', models.IntegerField()),
                ('average', models.IntegerField(blank=True, null=True)),
                ('strikerate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
