# Generated by Django 2.1.1 on 2019-06-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_batting_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=1024)),
                ('commodity', models.CharField(max_length=1024)),
                ('finyear', models.CharField(max_length=256)),
                ('decimalValue', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('isAboveThreshold', models.BooleanField(default=False)),
                ('isOtherItem', models.BooleanField(default=False)),
            ],
        ),
    ]
